#!/bin/bash
set -eu -o pipefail
if [ $# -eq 0 ]; then
  echo "Usage: $0 [init|update]" 1>&2
  exit 1
fi
mode="$1"
out_file='route2port.conf'
echo "Compiling new apache .conf to ${out_file}..."
python3 compile.py config.yaml ${out_file}
echo "Compilation complete."
sudo cp ${out_file} /etc/apache2/sites-available
cd /etc/apache2/sites-available
if [ $mode == "init" ]; then
  sudo a2ensite ${out_file}
fi
echo 'Running systemctl reload apache2...'
sudo systemctl reload apache2
